feat: update for languages and currencies
shopware/acceptance-test-suite pull request #175
Opened 2024-11-15 13:29 UTC by ravenokko

Added additional lcators for storefront

2024-11-22 15:07 UTC, yusufttur approved these changes, later dismissed

2024-12-12 07:39 UTC, vanpham-sw approved these changes, later dismissed

2024-12-12 07:45 UTC, frobel requested changes

2024-12-12 07:45 UTC, frobel commented on src/services/TestDataService.ts
> +    async createSalesChannelDomain(overrides: Partial<SalesChannelDomain> = {}): Promise<SalesChannelDomain>  {
could you please put that method to the area where all other create methods are located in the TestDataService?

2024-12-12 07:45 UTC, frobel commented on src/services/TestDataService.ts
> +    getSalesChannelDomainStruct(
could you please put that method to the area where all other get methods are located in the TestDataService?

2024-12-13 06:42 UTC, frobel approved these changes

2024-12-13 09:03 UTC, GitEvil approved these changes

2024-12-13 09:05 UTC, sguder approved these changes

2024-12-13 10:15 UTC, merged