fix: NEXT-39784 - fix and add some locators to AccountProfile and Acc…
shopware/acceptance-test-suite pull request #240
Opened 2024-12-17 15:43 UTC by ocavli

needed to adjust some locators and add some news to the pages.

2024-12-17 16:12 UTC, frobel requested changes

2024-12-17 16:12 UTC, frobel commented on src/page-objects/storefront/AccountProfile.ts
> +
```suggestion
```

2024-12-18 08:01 UTC, ocavli commented on src/page-objects/storefront/AccountProfile.ts
> +
fixed 👍

2024-12-18 08:19 UTC, frobel approved these changes

2024-12-18 08:32 UTC, merged