NEXT-39675 - Flow Builder Templates
shopware/acceptance-test-suite pull request #246
Opened 2024-12-19 08:42 UTC by GitEvil

Adds Flow Builder Templates page object
Adds locators to Flow Builder Create, Listing and Detail

2025-02-13 03:45 UTC, vanpham-sw commented on src/services/ShopwareDataHelpers.ts
> +export const getFlowTemplateData = async (flowTemplateId: string, adminApiContext: AdminApiContext): Promise<FlowTemplate> => {
```suggestion
export const getFlowTemplate = async (flowTemplateId: string, adminApiContext: AdminApiContext): Promise<FlowTemplate> => {
```

2025-02-13 03:45 UTC, vanpham-sw commented on src/services/ShopwareDataHelpers.ts
> +export const getFlowData = async (flowId: string, adminApiContext: AdminApiContext): Promise<Flow> => {
```suggestion
export const getFlow = async (flowId: string, adminApiContext: AdminApiContext): Promise<Flow> => {
```

2025-03-17 15:09 UTC, frobel requested changes

2025-03-17 15:09 UTC, frobel commented on src/page-objects/administration/FlowBuilderCreate.ts
> +    url(flowId?: string, tabName = 'general') {
Is it possible to go to another tab without using a flowId? If so we have to switch the arguments of the `URL()`. 

Because if not you have to add a flowId everytime, even if that is an optional parameter.

2025-03-17 15:09 UTC, frobel commented on src/page-objects/administration/FlowBuilderDetail.ts
> +        this.templateName = page.getByLabel(('Name'));
```suggestion
        this.templateName = page.getByLabel('Name');
```

2025-03-17 15:09 UTC, frobel commented on src/page-objects/administration/FlowBuilderDetail.ts
> +        this.flowName = page.getByTestId('sw-field--flow-name');
Sure with that Locator getByTestId? We never used it before.

2025-03-17 15:09 UTC, frobel commented on src/page-objects/administration/FlowBuilderTemplates.ts
> +    async getLineItemByFlowName(flowName: string): Promise<Record<string, Locator>> {
```suggestion
    async getLineItemByFlowName(flowName: string) {
```

2025-03-17 15:09 UTC, frobel commented on src/page-objects/administration/FlowBuilderTemplates.ts
> +        const createFlowLink = lineItem.getByRole('link').getByTestId('sw-icon__regular-long-arrow-right');
Why you are using again getByTestId?

2025-03-18 22:53 UTC, GitEvil commented on src/page-objects/administration/FlowBuilderDetail.ts
> +        this.flowName = page.getByTestId('sw-field--flow-name');
Playwright documentation suggests using _getByTestId_ as the most resilient way of writing tests. However, it also states that this is not user-facing, so I agree to change them.

2025-03-18 22:54 UTC, GitEvil commented on src/page-objects/administration/FlowBuilderTemplates.ts
> +        const createFlowLink = lineItem.getByRole('link').getByTestId('sw-icon__regular-long-arrow-right');
I'm not sure why, but I think I found a better way now. 👌

2025-03-18 23:33 UTC, GitEvil commented on src/page-objects/administration/FlowBuilderCreate.ts
> +    url(flowId?: string, tabName = 'general') {
If you change tabs the flowId stays the same, so I guess that means it is not possible. But let's have a quick chat.

2025-03-20 07:06 UTC, frobel commented on src/page-objects/administration/FlowBuilderCreate.ts
> +    url(flowId?: string, tabName = 'general') {
I double check and we have build in a special case that on the create page we could have just the path: `...create/tabName` and also `...create/flowId/tabName` if you create a new flow out of a template

2025-03-20 07:07 UTC, frobel commented on src/page-objects/administration/FlowBuilderDetail.ts
> +        this.flowName = page.getByTestId('sw-field--flow-name');
yes it is possibnle but we wantn to use the user-facing locators first ;)

2025-03-20 11:08 UTC, frobel requested changes

2025-03-20 11:08 UTC, frobel commented on src/page-objects/administration/FlowBuilderCreate.ts
>          this.newFlowHeader = page.getByRole('heading', { name: 'New flow' })
```suggestion
        this.newFlowHeader = page.getByRole('heading', { name: 'New flow' });
```

2025-03-20 11:08 UTC, frobel commented on src/page-objects/administration/FlowBuilderTemplates.ts
> +import type { Page, Locator } from '@playwright/test';
```suggestion
import type { Page } from '@playwright/test';
```

2025-03-20 12:30 UTC, frobel approved these changes

2025-03-20 12:30 UTC, frobel commented on src/page-objects/AdministrationPages.ts
> +    AdminFlowBuilderTemplates: FlowBuilderTemplates
```suggestion
    AdminFlowBuilderTemplates: FlowBuilderTemplates;
```

2025-03-20 12:48 UTC, frobel approved these changes

2025-03-20 13:26 UTC, merged