fix: example for locator comatibility in shopware versions
shopware/acceptance-test-suite pull request #249
Opened 2024-12-20 19:57 UTC by frobel

2025-01-02 08:29 UTC, frobel commented on src/page-objects/administration/CustomerListing.ts
> +        if(satisfies(instanceMeta.version, '<6.7')){
For platform PRs (running test pipeline with major feature flag) there is another possibility:

https://github.com/shopware/shopware/pull/5973

2025-01-02 12:57 UTC, yusufttur requested changes

2025-01-02 12:57 UTC, yusufttur commented on src/page-objects/administration/CustomerListing.ts
> +        if(satisfies(instanceMeta.version, '<6.7')){
@frobel This doesn't work for 6.7 instances, even major feature flag is activated, it returns `6.6.9999999.9999999-dev` as version number.

2025-01-02 16:21 UTC, frobel commented on src/page-objects/administration/CustomerListing.ts
> +        if(satisfies(instanceMeta.version, '<6.7')){
yes true, @pweyck want to provide a fix so that we get back 6.7.999.999-dev

2025-01-03 12:46 UTC, pweyck commented on src/page-objects/administration/CustomerListing.ts
> +        if(satisfies(instanceMeta.version, '<6.7')){
https://github.com/shopware/shopware/pull/5993

2025-02-05 10:50 UTC, closed without merging